### PR TITLE
Make an unauthenticated request to fetch the region cache on login

### LINKED ISSUE #598: Fail to login via SSH if the region cache is not present
If a user tries to login via SSH when the region cache is not present, we will try to make an authenticated request to get the region list wich fails since the user is not authenticated.

### PR DESCRIPTION
**Pull request by johnsudaar**
Fix #598

- [x] Add a changelog entry in the section "To Be Released" of CHANGELOG.md

### CODE REVIEW

**Comment by johnsudaar** [comment]
Waiting for https://github.com/Scalingo/go-scalingo/pull/180

File: config/region.go [hunk 1]
```diff
@@ -50,27 +51,41 @@ func EnsureRegionsCache(c Config, opts GetRegionOpts) (RegionsCache, error) {
...
 	regions, err := client.RegionsList()
 	if err != nil {
 		return RegionsCache{}, errgo.Notef(err, "fail to list available regions")
 	}
 
 	regionsCache.Regions = regions
 	regionsCache.ExpireAt = time.Now().Add(10 * time.Minute)
+
+	if opts.SkipAuth {
+		return regionsCache, nil
```
Comment (EtienneM) [inline config/region.go:86]: Why don't you write the regions cache in case you skip the auth? I have my idea on this matter but it might be interesting to explain it in a comment here.

**Review by EtienneM — APPROVED** [review]
