### PR TITLE
Fix creation of an integration link

### LINKED ISSUE #509: [Integration Link] Unable to create integration link for an app
Example :
```bash
scalingo -a gitlab-test integration-link-create https://gitlab.example.com/Scalingo/sample-go-martini
? Branch to auto-deploy (empty to disable): master
? Automatically deploy review apps: Yes
? Automatically destroy review apps when the pull/merge request is closed: Yes
? Hours before automatically destroying the review apps: 0
? Automatically destroy review apps after some time without deploy/commits: Yes
? Hours before automatically destroying the review apps: 0
 !     An error occured:
       fail to get the integration link for this app: fail to get this SCM repo link: The scm_repo_link was not found
```

It's for all SCM type not only GitLab.

### PR DESCRIPTION
**Pull request by brandon-welsch**
Fix #509

### CODE REVIEW

File: integrationlink/create.go [hunk 1]
```diff
@@ -28,10 +28,7 @@ func Create(app string, integrationType scalingo.SCMType, integrationURL string,
 		return errgo.Notef(err, "fail to get the integration")
 	}
 
-	repoLink, err := c.SCMRepoLinkShow(app)
-	if err != nil {
```
Comment (EtienneM) [inline integrationlink/create.go]: I don't really like that you completely remove the error checking. Can't you just ignore the error in case it's a 404?

File: integrationlink/create.go [hunk 2]
```diff
@@ -29,7 +30,7 @@ func Create(app string, integrationType scalingo.SCMType, integrationURL string,
 	}
 
 	repoLink, err := c.SCMRepoLinkShow(app)
-	if err != nil {
+	if scerr, ok := errors.ErrgoRoot(err).(*http.RequestFailedError); ok && scerr.Code != 404 {
```
Comment (EtienneM) [inline integrationlink/create.go]: What happens if the error type is not `http.RequestFailedError`?

Comment (EtienneM) [reply integrationlink/create.go]: Here, you are ignoring the error if it's a 404 or if it's anything else but a `http.RequestFailedError`. I think the intended behaviour is to ignore the error only in case of a 404, isn't it?

Comment (brandon-welsch) [reply integrationlink/create.go]: I return errors only if it's not 404, if the error is a 404 the code is executed normally. 

I don't understand, it's written in the code ^^

Comment (EtienneM) [reply integrationlink/create.go]: I mean that you MUST return if the error is not a `http.RequestFailedError`. And it's not the case.

Comment (brandon-welsch) [reply integrationlink/create.go]: Hmmm ok
