### PR TITLE
fix(install): for MacOS compatibility, remove usage of long parameter for cut and tr

### LINKED ISSUE #1001: [MacOS] Install script failed due to usage of long parameters
https://app.intercom.com/a/inbox/w4oogu7s/inbox/shared/all/conversation/12375700189899

On MacOS the current install script fails on `tr` and `cut` command due to long parameters, e.g.
```bash
$ curl -O https://cli-dl.scalingo.com/install && bash install
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 5091 0 5091 0 0 68495 0 --:--:-- --:--:-- --:--:-- 71704
tr: illegal option -- -
usage: tr [-Ccsu] string1 string2
tr [-Ccu] -d string1
tr [-Ccu] -s string1
tr [-Ccu] -ds string1 string2
! Fail to get the version of the CLI
! You probably have an old version of curl. Please check your curl version and update accordingly.
```
Or
```bash
-----> Downloading Scalingo client... DONE
-----> Verifying the checksum... install: line 135: sha256sum: command not found
cut: illegal option -- -
usage: cut -b list [-n] [file ...]
cut -c list [file ...]
cut -f list [-s] [-w | -d delim] [file ...]
install: line 136: wget: command not found
cut: illegal option -- -
usage: cut -b list [-n] [file ...]
cut -c list [file ...]
cut -f list [-s] [-w | -d delim] [file ...]
VALID
-----> Extracting... DONE
-----> Install Scalingo client to /opt/homebrew/bin
sudo required...
/opt/homebrew/bin does not exist, creating...
-----> Installation completed, the command 'scalingo' is available.
install: line 196: scalingo: command not found
-----> Here's what's new in this version:
```

Note that the installation path is: `/opt/homebrew/bin` and seems not in the PATH by default.

Regression has been added in #988 : https://github.com/Scalingo/cli/pull/988/commits/5efcc9f56185b652ca5c9ea35cc0299cec38ee8d

### PR DESCRIPTION
**Pull request by curzolapierre**
~~- [ ] Add a changelog entry in the section "To Be Released" of CHANGELOG.md~~

Fixes #1001

### CODE REVIEW

File: dists/install.sh [hunk 1]
```diff
@@ -110,7 +118,7 @@ main() {
   tmpdir=$(mktemp -d /tmp/scalingo_cli_XXX)
   trap "clean_install ${tmpdir}" EXIT
 
-  version=$(curl --silent https://cli-dl.scalingo.com/version | tr --delete ' \t\n')
+  version=$(curl --silent https://cli-dl.scalingo.com/version | tr -d ' \t\n')
```
Comment (EtienneM) [inline dists/install.sh:121]: question(non blocking): Maybe add a comment everywhere you use short option to explain the reason? As the Scalingo good practice is to use long options, we will maybe be tempted to update these options again in the future.
