### PR TITLE
fix(addons): parse `maintenance-window-hour` as an int

### LINKED ISSUE #1219: [`addons-config `] `--maintenance-window-hour` always set the same hour, whatever the value
```
sscalingo --app REDACTED addons-config ad-REDACTED --maintenance-window-hour 3
Addon config updated.
```

But on the dashboard:

Image

With the debug output, we can see that the payload sent to the API is always the same.

Notify when fixed: https://www.notion.so/HULK-3604

### PR DESCRIPTION
**Pull request by EtienneM**
```
bsscalingo --app REDACTED addons-config ad-REDACTED --maintenance-window-hour 3
Addon config updated.
```

And now on the dashboard:

image

Fix #1219 

- [x] Add a changelog entry in the section "To Be Released" of CHANGELOG.md

### CODE REVIEW

File: cmd/addons.go [hunk 1]
```diff
@@ -183,7 +183,7 @@ var (
 		Category: "Addons",
 		Usage:    "Configure an add-on attached to your app",
 		Flags: []cli.Flag{&appFlag,
-			&cli.StringFlag{Name: "maintenance-window-hour", Usage: "Configure add-on maintenance window starting hour (in your local timezone)"},
+			&cli.IntFlag{Name: "maintenance-window-hour", Usage: "Configure add-on maintenance window starting hour (in your local timezone)"},
```
Comment (EtienneM) [inline cmd/addons.go:186]: This is the fix. The rest is just a variable renaming.

**Review by curzolapierre — APPROVED** [review]
Thanks for the fix 🙏 

LGTM
