### PR TITLE
fix(logdrains): delete Logentries mentions

### LINKED ISSUE #819: Remove Logentries
Logentries is shutting down.

### PR DESCRIPTION
**Pull request by EtienneM**
Will be merged the 15th of November 2022.

I also renamed the package `log_drains` to `logdrains` as it's a convention in Go that packages name don't contain `_`.

Fix #819

n/a:
- [ ] Add a changelog entry in the section "To Be Released" of CHANGELOG.md

### CODE REVIEW

File: cmd/log_drains.go [hunk 1]
```diff
@@ -76,7 +76,6 @@ var (
 		$ scalingo --app my-app log-drains-add --type appsignal --token 123456789abcdef
 		$ scalingo --app my-app log-drains-add --type datadog --token 123456789abcdef --drain-region eu-west-2
 		$ scalingo --app my-app log-drains-add --type ovh-graylog --token 123456789abcdef --host tag3.logs.ovh.com
-		$ scalingo --app my-app log-drains-add --type logentries --token 123456789abcdef
```
Comment (EtienneM) [inline cmd/log_drains.go:79]: This is actually the only mention of Logentries in the CLI code base

**Review by curzolapierre — APPROVED** [review]
LGTM
