### PR TITLE
fix(cli): return an exit code equal to 1 when a command or flag is malformed

### LINKED ISSUE #947: No exit code is returned when command 'integration-link-manual-deploy' execution has failed
Actually no exit code is returned when the following command fails : 
` scalingo --app my-app integration-link-manual-deploy --branch "my-branch"`
`Incorrect Usage: flag provided but not defined: -branch`

When running `echo $?` the result is 0 (successful) 

**Expected result**
When the command execution fails, the exit code shoud be other than 0.
`echo $?` should be other than 0.

ℹ️  I have seen it on this command but maybe is common to all commands.

### PR DESCRIPTION
**Pull request by Soulou**
Fixes #947

- [x] Add a changelog entry in the section "To Be Released" of CHANGELOG.md

### CODE REVIEW

File: scalingo/main.go [hunk 1]
```diff
@@ -127,14 +129,24 @@ func main() {
...
-	if err := app.RunContext(ctx, os.Args); err != nil {
+	err := app.RunContext(ctx, os.Args)
+	if err != nil {
 		fmt.Println("Fail to run command:", err)
 	}
+
+	// We want to display to the user if a new version is available
+	// Whatever the success of the execution of their command is.
+	updateCheckErr := update.Check()
+	if err != nil {
```
Comment (yohann-bacha) [inline scalingo/main.go:145]: **issue:** isn't it updateCheckErr you should check?

**Review by yohann-bacha — CHANGES_REQUESTED** [review]

File: scalingo/main.go (hunk 1 above)
Comment (Soulou) [reply scalingo/main.go]: You're 100% right

**Review by yohann-bacha — APPROVED** [review]

**Comment by teddyanoloc** [comment]
thank you very much for this quick fix ! 👍
