### PR TITLE
fix(cmd): addons-info working for non-db addons

### LINKED ISSUE #1054: addons-info not working for non database addons

### PR DESCRIPTION
**Pull request by curzolapierre**
- [x] Add a changelog entry in the section "To Be Released" of CHANGELOG.md

```sh
 ➜  scalingo --app $APPNAME addons-info ad-42d531f2-c985-47b9-b7f1-6771c8ced235
+----------------+-----------------------+
| Addon Provider | Scalingo Docker Image |
| Plan           | base-plan             |
| Status         | running               |
+----------------+-----------------------+
 ➜  scalingo --app $APPNAME addons-info ad-5656af19-eda5-4f00-afec-3c1cd726f960
+----------------+--------------------+
| Addon Provider | Scalingo VPN IPSec |
| Plan           | vpn-ipsec-standard |
| Status         | running            |
+----------------+--------------------+
 ➜  scalingo --app $APPNAME addons-info postgresql
+------------------------+--------------------------------+
| Addon Provider         | PostgreSQL                     |
| Plan                   | postgresql-starter-512         |
| Status                 | running                        |
| Database Type          | postgresql                     |
| Version                | 14.9.0-1                       |
| Force TLS              | disabled                       |
| Internet Accessibility | disabled                       |
| Maintenance window     | Wednesdays at 15:00 (08 hours) |
+------------------------+--------------------------------+
```

Fixes #1054

### CODE REVIEW

File: db/utils.go [hunk 1]
```diff
@@ -0,0 +1,5 @@
+package db
+
+var (
+	SupportedDatabases = []string{"PostgreSQL", "InfluxDB", "MongoDB", "MySQL"}
```
Comment (ipfaze) [inline db/utils.go:4]: question: no Redis? no Elasticsearch?

File: addons/info.go [hunk 2]
```diff
@@ -7,31 +7,61 @@ import (
...
 	if err != nil {
-		return errgo.Notef(err, "fail to get addon information")
+		return errors.Wrap(ctx, err, "get addon information")
+	}
+
+	isDatabase := slices.ContainsFunc(db.SupportedDatabases, func(s string) bool {
+		return strings.EqualFold(s, addonInfo.AddonProvider.ID)
+	})
+
+	dbInfo := [][]string{}
```
Comment (ipfaze) [inline addons/info.go:40]: nitpick: `dbInfo` is used for database information but also for other addon information after the condition.
I suggest:
```suggestion
	addonInfo := [][]string{}
```

File: addons/info.go [hunk 3]
```diff
@@ -7,31 +7,61 @@ import (
...
+	if isDatabase {
+		dbInfo, err = getDatabaseInfo(ctx, c, app, addon)
+		if err != nil {
+			return errors.Wrap(ctx, err, "get database information")
+		}
 	}
 
+	t := tablewriter.NewWriter(os.Stdout)
+	t.Append([]string{"Addon Provider", addonInfo.AddonProvider.Name})
```
Comment (ipfaze) [inline addons/info.go:49]: question: why not filled the `dbInfo` struct like the one in the `getDatabaseInfo` function?
Example:
```go
    lines := [][]string{
        {"Database Type", dbInfo.TypeName},
	...
    }

**Review by ipfaze — COMMENTED** [review]
Some questions and nitpicks otherwise LGTM :+1:

File: addons/info.go (hunk 2 above)
Comment (curzolapierre) [reply addons/info.go:40]: This variable only contains database information, or I don't see which condition are you talking about. I surely miss something here, could you point me where exactly please?

Comment (ipfaze) [reply addons/info.go:40]: :facepalm: my bad, I misread the code. You're right!

**Review by ipfaze — APPROVED** [review]
LGTM :+1:
