### PR TITLE
fix(notifier): no-event notifier

### LINKED ISSUE #777: `scalingo notifiers`: crashes if no-event notifier exists
It is possible for "no-event" notifiers to exist on applications.

With Scalingo CLI 1.24.2, when displaying the list of notifiers for an application that has such a notifier, the CLI crashes.

## How to reproduce

1. Create a no-event notifier on the current app:
```
$ scalingo notifiers-add --name test --platform email
+-----------------+-----------------------------------------+
| ID              | …                                       |
| Type            | email                                   |
| Name            | test                                    |
| Enabled         | true                                    |
| Send all events | false                                   |
| Emails          | []                                      |
| User_ids        | []                                      |
| Selected events |                                         |
+-----------------+-----------------------------------------+
-----> Notifier have been created.
```
(btw there's a typo here, it should read `Notifier has been created`).

2. Try to list the notifiers of the app with `scalingo notifiers`:
```
$ scalingo notifiers
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/Scalingo/cli/notifiers.eventTypesToString({0x1400058d000, 0x25, 0x2a}, {0x103706588, 0x0, 0x0})
	/home/runner/work/cli/cli/notifiers/list.go:62 +0x180
github.com/Scalingo/cli/notifiers.List({0x16d2337e4, 0x12})
	/home/runner/work/cli/cli/notifiers/list.go:36 +0x31c
github.com/Scalingo/cli/cmd.glob..func133(0x14000160c60)
	/home/runner/work/cli/cli/cmd/notifiers.go:27 +0x4c
github.com/Scalingo/cli/cmd.(*AppCommands).addCommand.func1(0x14000160c60)
	/home/runner/work/cli/cli/cmd/commands.go:67 +0x2ec
github.com/urfave/cli.HandleAction({0x1031ff7c0, 0x140002262d0}, 0x14000160c60)
	/home/runner/work/cli/cli/vendor/github.com/urfave/cli/app.go:526 +0x60
github.com/urfave/cli.Command.Run({{0x1030decaa, 0x9}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1030e663f, 0x13}, {0x0, ...}, ...}, ...)
	/home/runner/work/cli/cli/vendor/github.com/urfave/cli/command.go:173 +0x610
github.com/urfave/cli.(*App).Run(0x140001d2700, {0x14000132040, 0x4, 0x4})
	/home/runner/work/cli/cli/vendor/github.com/urfave/cli/app.go:277 +0x60c
main.main()
	/home/runner/work/cli/cli/scalingo/main.go:158 +0x648
```

Expected behavior: show the list of notifiers.

### PR DESCRIPTION
**Pull request by QuentinEscudierScalingo**
Fix the crash when trying to list a no-event notifier
Fix the typo Notifier have been created -> Notifier has been createdFixes #777

Fixes #777

### CODE REVIEW

File: notifiers/list.go [hunk 1]
```diff
@@ -48,6 +48,10 @@ func List(ctx context.Context, app string) error {
 }
 
 func eventTypesToString(eventTypes []scalingo.EventType, ids []string) (res string) {
+	if len(ids) == 0 {
+		res = ""
+		return
```
Comment (curzolapierre) [inline notifiers/list.go:53]: It is not related to your code but could you please replace the "naked" returns by return with the variable name as it is not correspond to our style guide.
It is usually appreciated to improve the legacy code when you can, if you have time to do it :)

**Review by curzolapierre — COMMENTED** [review]
Just a comment related to the legacy code present, but the fix LGTM :+1:

**Review by curzolapierre — APPROVED** [review]
LGTM
